spring:
  application:
    name: participant-tracker

  data:
    mongodb:
      database: local

logging:
  file:
    path: /tmp/participant-tracker

ui-settings:
  result-view:
    number-of-columns: 26

backend-settings:
  laps:
    registration-grace-period: 15
---
spring:
  profiles: dev

  data:
    mongodb:
      database: test
#      authentication-database: admin
#      username: admin
#      password: bbutinbunketorp

---
spring:
  profiles: demo

demo:
 participants-to-generate: 8

