spring:
  application:
    name: participant-tracker

  data:
    mongodb:
      database: prod
#      authentication-database: admin
#      username: admin
#      password: bbutinbunketorp

logging:
  file:
    name: /tmp/logs/participant-tracker.log
  level:
    org.ikuven.bbut.tracking: INFO
    org.springframework.web: INFO

ui-settings:
  result-view:
    number-of-columns: 26
    show-teams-column: true

backend-settings:
  laps:
    registration-grace-period: 15
---
spring:
  profiles: dev

  data:
    mongodb:
      database: test
#      authentication-database: admin
#      username: admin
#      password: bbutinbunketorp

---
spring:
  profiles: demo

demo:
 participants-to-generate: 0

---
spring:
  profiles: debug

logging:
  level:
    org.ikuven.bbut.tracking: DEBUG
    org.springframework.web: DEBUG
