spring:
  application:
    name: result-tracker

  data:
    mongodb:
      database: local

participant:
  lap:
    registration-grace-period: 15

---
spring:
  profiles: dev

  data:
    mongodb:
      database: test


